apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: crogeriorl/kube-news:v1
        env:
        - name:  DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: db_database
        - name:  DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: db_username
        - name:  DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: db_password
        - name:  DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: db_host
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  type: NodePort