apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: kubenews
          image: crogeriorl/kube-news:v27
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: db_database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: db_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: db_host
