apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubenews
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubenews
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: kubenews
          image: crogeriorl/kube-news:v27
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "384Mi"
              cpu: "384m"
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: pdb_database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: mdb_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: mdb_password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: pdb_host
