# This is a basic workflow to help you get started with Actions

name: CI/CD kubenews

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - src/**    # only changes in src/ starts this CI
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "CI"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            crogeriorl/kube-news:latest
            crogeriorl/kube-news:v${{github.run_number}}
  # CD:
  #   runs-on: ubuntu-latest
  #   needs: [CI]    # depends on 'CI' job
  #   steps:
  #     - uses: actions/checkout@v3
      
  #     - name: Kubernetes Set Context
  #       uses: Azure/k8s-set-context@v2
  #       with:
  #         method: kubeconfig
  #         kubeconfig: ${{secrets.K8S_CONFIG}}

  #     - name: Deploy to Kubernetes cluster
  #       uses: Azure/k8s-deploy@v3.1
  #       with:
  #         images: crogeriorl/kube-news:v${{github.run_number}}
  #         manifests: |
  #           k8s/deployment.yaml
  #           k8s/secrets.yaml
  CD:  
    runs-on: ubuntu-latest
    needs: [CI]    # depends on 'CI' job
    steps:
    - name: install yq
      uses: mikefarah/yq@v4.15.1

    - name: update infra yaml file
      run: |
        cd k8s
        yq e -i '.spec.template.spec.containers[0].image="https://hub.docker.com/repository/docker/crogeriorl/kube-news:v${{github.run_number}}"' deployment.yaml
        cat deployment.yaml

    - name: push change
      uses: dmnemec/copy_file_to_another_repo_action@main
      #env:
      #  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: k8s/deployment.yaml
        destination_repo: crogeriorl/kube-news
        destination_branch: main
        destination_folder: k8s
        user_email: crogeriolopes@gmail.com
        user_name: crogeriorl
        commit_message: update image version ${{ steps.get_version.outputs.VERSION }}